### ISSUE TITLE
Newest Version doesn't work

### ISSUE THREAD

**Issue by dhinojosa** [jangaraj/keycloak-gitpod#1]
I have been trying to find a solution for the latest version of Keycloak. I am still not making progress; I'll submit a PR if found.

**Comment by jangaraj** [comment]
It works for me:
![obrázok](https://github.com/user-attachments/assets/8aafa882-22da-470e-9a01-2697578b60f4)

It would help if you were more specific.

**Comment by dhinojosa** [comment]
Sorry, I meant the latest keycloak, version 26.0.5, not 12.0.4 :)

I created this docker-compose, and it is tough to figure out. I tried using your settings, but they have changed quite a bit.  

https://github.com/dhinojosa/gitpod-keycloak-isolated

https://github.com/dhinojosa/gitpod-keycloak-isolated/blob/main/docker-compose.yaml
